### ISSUE TITLE
Update carpark bucket

### ISSUE THREAD

**Issue by vasco-santos** [w3s-project/w3infra#263]
# carpark bucket plan

See proposal at https://hackmd.io/@vasco-santos/r17aSScE6

**Comment by vasco-santos** [comment]
Goal is mostly for R2

**Comment by olizilla** [comment]
we should plan to change the bucket name in the dynamo indexes so we can tell from the index record where in r2 that block lives.

Currently the indexes tell us where in s3 they live, and we just optimistically try R2 first. Ideally we would tweak the new records to include some info that R2 is the primary source for the new writes. 

Some (possibly bad) ideas to get the ball rolling.

- we have a `region` field in the indexes. we could set that to `auto` for indexes that are primarily R2. aws doesn't have an `auto` region while R2 recommends it.
  - good because it fits int the exiting schema.
  - bad because it's a subtle workaround rather than explicit
- we add an extra property to the indexes, and check that.
- switch to using content claims everywhere?
- do nothing, and have each consumer try r2:carpark-prod-1 then r2:carpark-prod-0, then aws:carpark-prod-1... (my least favourite option.

**Comment by olizilla** [comment]
Here is where we optimistically try R2 carpark if the key structure we find in the dynamo index is either carCID based or one we can derive the car cid key from https://github.com/web3-storage/hoverboard/blob/26b06e6312863d77619357cabdc8b9954f71964e/src/blocks.js#L130-L154

**Comment by reidlw** [comment]
@vasco-santos what's the status of this?

**Comment by vasco-santos** [comment]
@reidlw this may be part of the bigger data anywhere project that has been mostly stalled over last month. We will need to decide if this is still important to do, or with upcoming plans to decentralize write target we do not plan to do this anymore. Can you let me know the context of the question to better understand where we currently stand requirements wise?

**Comment by vasco-santos** [comment]
blob protocol is writing to other bucket
